# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fb38fcc704f3d71f9fa19e8349e1493e3eada2f9ba367aa2f54b00ec22b9b204058e25bff9071ead01d93120c3b469f84e44f9c5adb1f1f3e7cede0ffd19b0d

test:
  secret_key_base: c7e6ac60df40353b045b4db51e6af46384382b7644c3f9c9a2d543331128c6331070ad1404d7db4778fa2feed31c8964b6a5aad51a428a6fa2258e9aae5dd33d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
